function [fitresult, gof, xData, yData] = createFit(xAxisLifetimeForFit, normalizedLifetimeMaxToNoiseForFit)
%CREATEFIT(XAXISLIFETIMEFORFIT,NORMALIZEDLIFETIMEMAXTONOISEFORFIT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xAxisLifetimeForFit
%      Y Output: normalizedLifetimeMaxToNoiseForFit
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Jul-2022 17:10:21


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xAxisLifetimeForFit, normalizedLifetimeMaxToNoiseForFit );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares', 'MaxIter', 1000000  );
opts.Display = 'Off';


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );




